n1=int(input())
n2=int(input())
print("Assignment operators")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1//n2)
print(n1%n2)
print("logical operators")
print(n1 and n2)
print(n1 or n2)
print(not(n1))
print("Comparison operators")
print(n1==n2)
print(n1>n2)
print(n1<n2)
print(n1!=n2)
print("Identity operators")
print(n1 is n2)
print(n2 is not n1)
